/** Generated by scripts/generate-docs.js. */
export const buildInfo = {
  "version": "4.2.0",
  "languageCount": 32,
  "supportedLanguages": [
    {
      "code": "ko",
      "label": "한국어"
    },
    {
      "code": "ja",
      "label": "日本語"
    },
    {
      "code": "zh-CN",
      "label": "中文(简体)"
    },
    {
      "code": "zh-TW",
      "label": "中文(繁體)"
    },
    {
      "code": "es",
      "label": "Español"
    },
    {
      "code": "fr",
      "label": "Français"
    },
    {
      "code": "it",
      "label": "Italiano"
    },
    {
      "code": "nl",
      "label": "Nederlands"
    },
    {
      "code": "de",
      "label": "Deutsch"
    },
    {
      "code": "pt-BR",
      "label": "Português (BR)"
    },
    {
      "code": "ru",
      "label": "Русский"
    },
    {
      "code": "vi",
      "label": "Tiếng Việt"
    },
    {
      "code": "id",
      "label": "Bahasa Indonesia"
    },
    {
      "code": "en",
      "label": "English"
    },
    {
      "code": "pt",
      "label": "Português (PT)"
    },
    {
      "code": "pl",
      "label": "Polski"
    },
    {
      "code": "uk",
      "label": "Українська"
    },
    {
      "code": "cs",
      "label": "Čeština"
    },
    {
      "code": "sv",
      "label": "Svenska"
    },
    {
      "code": "da",
      "label": "Dansk"
    },
    {
      "code": "fi",
      "label": "Suomi"
    },
    {
      "code": "no",
      "label": "Norsk"
    },
    {
      "code": "tr",
      "label": "Türkçe"
    },
    {
      "code": "ar",
      "label": "العربية"
    },
    {
      "code": "hi",
      "label": "हिन्दी"
    },
    {
      "code": "th",
      "label": "ภาษาไทย"
    },
    {
      "code": "ms",
      "label": "Bahasa Melayu"
    },
    {
      "code": "tl",
      "label": "Filipino"
    },
    {
      "code": "bn",
      "label": "বাংলা"
    },
    {
      "code": "he",
      "label": "עברית"
    },
    {
      "code": "ro",
      "label": "Română"
    },
    {
      "code": "hu",
      "label": "Magyar"
    },
    {
      "code": "el",
      "label": "Ελληνικά"
    }
  ]
} as const;
